import React, {
  useEffect,
  useState,
} from 'react'
import Head from 'next/head'

import { useStores } from '../hooks'
import CustomTable from '../components/table'

import 'react-virtualized/styles.css'
import styles from '../styles/Home.module.css'

const CELL = [
  'id',
  'name',
  'sales_id',
  'item_id',
  'qty',
  'consumen_name',
  'transaction_date',
]

const Home = () => {
  const { userStore } = useStores()
  const [list, setList] = useState([])

  useEffect(() => {
    const fetch = async () => {
      const res = await userStore.fetchSales()
      setList(res.data)
    }
    fetch()
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Delman.io technical test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {list?.length ? (<CustomTable data={list} cell={CELL} />) : null}
      </main>
    </div>
  )
}

export default Home
